---
- import_tasks: ntp.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 6

- import_tasks: chrony.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int > 6 

