- name: Configure systemd journald
  template: src=etc/systemd/journald.conf.j2 dest=/etc/systemd/journald.conf owner=root group=root mode=0640
  when: ansible_distribution_major_version|int >= 7
  notify: restart journald
  tags: ['journald', 'systemd-journald']
