- name: Install kerberos packages
  yum:
      name:
          - krb5-workstation
          - pam_krb5
          - cyrus-sasl-gssapi
      state: present
      update_cache: yes
  when: ansible_os_family == 'RedHat'
  tags: ['krb5', 'kerberos']
      

