---
- name: Disable default CentOS-Base repositories
  template: src=etc/yum.repos.d/CentOS-Base.repo.j2 dest=/etc/yum.repos.d/CentOS-Base.repo owner=root group=root mode=0644
  when: ansible_distribution == 'CentOS'
  tags: ['afilias','yum']

- name: Install EPEL GPG Key
  copy: src=etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }} dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }} owner=root group=root mode=0644
  when: ansible_os_family == 'RedHat'
  tags: ['afilias','yum']

