---
- name: Set up Afilias built package repositories (afilias-extras)
  template: src=etc/yum.repos.d/afilias-extras.repo.j2 dest=/etc/yum.repos.d/afilias-extras.repo owner=root group=root mode=0644
  when: ansible_os_family == 'RedHat'
  tags: ['afilias','yum']

