---
- name: Set up EPEL YUM repositories
  template: src=etc/yum.repos.d/afilias-epel.repo.j2 dest=/etc/yum.repos.d/afilias-epel.repo owner=root group=root mode=0644
  when: ansible_os_family == 'RedHat'
  tags: ['afilias','yum']

