- name: Check if audit=1 is already passed to the kernel
  shell: grep -E '^\s+kernel' /boot/grub/grub.conf | grep 'audit=1' | wc -l
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 6
  register: kernels
  changed_when: no
  failed_when: no
  tags: ['audit', 'auditd', 'auditsp', 'hardening', 'security', 'grub', 'grub2']

- name: Enable audit ealier at kernel boot time
  shell: sed -i 's/\(^[^# ]*kernel.*\)$/\1 audit=1/' /boot/grub/grub.conf
  ignore_errors: "{{ ansible_check_mode }}"
  when: (ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 6) and (kernels.stdout|int == 0)
  changed_when: kernels.stdout|int == 0
  tags: ['audit', 'auditd', 'auditsp', 'hardening', 'security', 'grub', 'grub2']
  
