- name: Ensure systemd is installed
  package: name={{ item }} state=present
  with_items:
      - systemd
      - systemd-libs
  when: ansible_os_family == 'RedHat'
  tags: ['semaphores']

- name: Set default file permissions and set  RemoveIPC to no
  template: src=etc/systemd/logind.conf.j2 dest=/etc/systemd/logind.conf owner=root group=root mode=0644
  notify: restart systemd-logind
  when: ansible_os_family == 'RedHat'
  tags: ['semaphores']

- name: Ensure systemd is started and enabled
  service: name=systemd-logind state=started enabled=yes
  when: ansible_os_family == 'RedHat'
  tags: ['semaphores']
  
