- name: Stop, disable and mask firewalld
  systemd: name=firewalld state=stopped enabled=no masked=yes
  ignore_errors: yes
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7
  tags: ['ip6tables', 'firewall']

- name: Install iptables for IPv6
  package: name=iptables-ipv6 state=present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 6
  tags: ['ip6tables', 'firewall']

- name: Install iptables-services
  package: name=iptables-services state=present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7
  tags: ['ip6tables', 'firewall']

- name: Setup ip6tables rules
  template: src=etc/sysconfig/ip6tables.j2 dest=/etc/sysconfig/ip6tables owner=root group=root mode=0600
  notify: restart ip6tables
  tags: ['ip6tables', 'firewall']

- name: Start and enable ip6tables service
  service: name=ip6tables state=started enabled=yes
  tags: ['ip6tables', 'firewall']

