---
- name: restrict list of ssh MAC algorithms
  lineinfile:
    destfile: /etc/ssh/sshd_config
    regexp: '(?i)^macs'
    line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'
    state: present
    insertafter: 'Protocol 2' 
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "7")
  notify: "restart sshd"
  tags: ['sshd', 'ssh-security']

- name: restrict list of ssh ciphers
  lineinfile:
    destfile: /etc/ssh/sshd_config
    regexp: '(?i)^ciphers'
    line: 'Ciphers aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,rijndael-cbc@lysator.liu.se'
    state: present
    insertafter: 'Protocol 2'
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "7")
  notify: "restart sshd"
  tags: ['sshd', 'ssh-security']

- name: restrict list of ssh Kexalgorithms
  lineinfile:
    destfile: /etc/ssh/sshd_config
    regexp: '(?i)^Kexalgorithms'
    line: 'Kexalgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1'
    state: present
    insertafter: 'Protocol 2'
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "7")
  notify: "restart sshd"
  tags: ['sshd', 'ssh-security']

# todo
# centos/redhat 6 support
# cipher changes
